# Generated by Django 4.2.3 on 2023-08-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_section_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='parent',
        ),
    ]
