# Generated by Django 4.2.3 on 2023-08-10 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MatchAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.answer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.answer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShortAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('only_digits', models.BooleanField()),
                ('ignore_case', models.BooleanField()),
                ('ignore_spaces', models.BooleanField()),
                ('ignore_border_spaces', models.BooleanField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.answer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderAnswerElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('correct_order', models.IntegerField()),
                ('order_answ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.orderanswer')),
            ],
        ),
        migrations.CreateModel(
            name='MatchAnswerValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_id', models.SmallIntegerField()),
                ('key_inid', models.SmallIntegerField()),
                ('title', models.TextField()),
                ('mansw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.matchanswer')),
            ],
        ),
        migrations.CreateModel(
            name='MatchAnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_id', models.SmallIntegerField()),
                ('title', models.TextField()),
                ('mansw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.matchanswer')),
            ],
        ),
        migrations.CreateModel(
            name='GivenAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('file', models.FileField(upload_to='%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.answer')),
            ],
        ),
        migrations.CreateModel(
            name='FewVariantsAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multy_correct', models.BooleanField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.answer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_id', models.SmallIntegerField()),
                ('correct', models.BooleanField()),
                ('title', models.TextField()),
                ('fvansw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.fewvariantsanswer')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='answ_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.answertype'),
        ),
    ]
